/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"

void Assert_GPIOA_Output(uint8_t portNumber){
	GPIOA_ODR |= (1 << portNumber); //Output data register
}

void initialize_GPIOA_LPTIM(){
	initialize_GPIOA_GPO_PP(7);
}

void initialize_GPIOA(uint8_t CLKportNumber, uint8_t DIOportNumber){
	// Set GPIO registers for TM1637
	// A3 PA4 as CLK (GP Output, Push Pull)
	// A2 PA3 as DIO (Open Drain, Pull Up)
	initialize_GPIOA_GPO_PP(CLKportNumber); //PA4
	initialize_GPIOA_OD_PU(DIOportNumber); //PA3
}

//GPIO Open Drain, Pull-Up
void initialize_GPIOA_OD_PU(uint8_t portNumber){
 	// Port A
 	GPIOA_MODER &= ~(0x03 << (portNumber*2));   // Reset MODER
	GPIOA_MODER |= (0x01 << (portNumber*2));   // 01: General purpose output mode
 	GPIOA_OSPEEDR &= ~(0x3 << (portNumber*2)); // Reset OSPEEDR
 	GPIOA_OSPEEDR |= (0x02 << (portNumber*2));  // 10: High-speed mode
 	GPIOA_OTYPER |= (1 << portNumber);         // 1: Output open-drain
 	GPIOA_PUPDR &= ~(0x03 << (portNumber*2));   // Reset PUPDR
 	GPIOA_PUPDR |= (0x01 << (portNumber*2));    // 01: Pull-up
 }

 //General Purpose Output, Push-Pull
 void initialize_GPIOA_GPO_PP(uint8_t portNumber){
 	//Set GPIO register
 	GPIOA_MODER &= ~(0x03 << (portNumber*2)); //Reset MODER
 	GPIOA_MODER |= (0x01 << (portNumber*2)); //01: General purpose output mode
 	GPIOA_OSPEEDR |= (0x02 << (portNumber*2)); //10: High speed mode
 	GPIOA_OTYPER &= ~(1 << portNumber); //0: Output push-pull (reset state)
 	GPIOA_PUPDR &= ~(0x03 << (portNumber*2)); //Reset
 	GPIOA_PUPDR |= (0x02 << (portNumber*2)); //01: Pull-up
 }

 void initialize_GPIOA_Output(uint8_t portNumber, uint8_t polarity){
	 if (polarity == 1)
		 GPIOA_ODR |= (1 << portNumber);
	 else
		 GPIOA_ODR &= ~(1 << portNumber);
 }

 void initialize_GPIO_AM2302(){
	 initialize_GPIOA_OD_PU((uint8_t)0);
	 initialize_GPIOA_Output((uint8_t)0, 1);
 }

 void intialize_GPIO_USART2(){
 	// Port A PIN1 D1 PA9 USART2_TX(1), PIN2 D0 PA10 USART2_RX(1)
 	GPIOA_MODER &= ~(1 << 18); // 10: Alternate function mode for PA9 Reset value: 0xEBFF FCFF for port A
 	GPIOA_MODER |= (1 << 19);
 	GPIOA_MODER &= ~(1 << 20); // 10: Alternate function mode for PA10 Reset value: 0xEBFF FCFF for port A
 	GPIOA_MODER |= (1 << 21);
 	GPIOA_AFRH |= (0x4 << 4); // PA9 = AF4(USART2_TX) D1 0100: AF4
 	GPIOA_AFRH |= (0x4 << 8); // PA10 = AF4(USART2_RX) D0 0100: AF4
 	GPIOA_OSPEEDR |= (0x2 << 18); // 10: High speed for PA9
 	GPIOA_OSPEEDR |= (0x2 << 20); // 10: High speed for PA10
 	GPIOA_OTYPER &= ~(1 << 9); // 0: Output push-pull (reset state) PA9
 	GPIOA_OTYPER &= ~(1 << 10); // 0: Output push-pull (reset state) PA10
 	GPIOA_PUPDR &= ~(0x3 << 18); // 10: Pull-down for PA9
 	GPIOA_PUPDR &= ~(0x3 << 20); // 00: No pull-up, pull-down for PA10
 	// pGPIOB_ODR default
 	// pGPIOB_IDR default
 	// pGPIOB_BSRR default
 	// pGPIOB_LCKR default
 	// pGPIOB_LCKR default

 	// PA0 USART2_CTS AF4, PA1 USART2_RTS/USART2_DE AF4
 	GPIOA_MODER &= ~(1 << 0); // 10: Alternate function mode for PA0 Reset value: 0xEBFF FCFF for port A
 	GPIOA_MODER |= (1 << 1);
 	GPIOA_MODER &= ~(1 << 2); // 10: Alternate function mode for PA1 Reset value: 0xEBFF FCFF for port A
 	GPIOA_MODER |= (1 << 3);
 	GPIOA_AFRL |= (0x4 << 0); // PA0 = AF4(USART2_CTS) D1 0100: AF4
 	GPIOA_AFRL |= (0x4 << 4); // PA1 = AF4(USART2_RTS/USART2_DE) D0 0100: AF4
 	GPIOA_OSPEEDR |= (0x2 << 0); // 10: High speed for PA0
 	GPIOA_OSPEEDR |= (0x2 << 2); // 10: High speed for PA1
 	GPIOA_PUPDR |= (0x2 << 0); // 10: Pull-down for PA0
 	GPIOA_PUPDR |= (0x2 << 2); // 10: Pull-down for PA1
 }
