/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"
#include "LPTIM.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
int main(void)
{
	//intialize_Clock();
	initialize_LSE_Clock();
	initialize_LPTIM1_Clock();
	initialize_GPIOA_Clock();
	initialize_GPIOA_GPO_PP(7);
	initialize_NVIC_LPTIM1();
	initialize_LPTIM();

	//Start the timer
	LPTIM1_Start_Continuous_Mode();
	//LPTIM_CR |= (1 << 2); //CNTSTRT: Timer start in Continuous mode This bit can be set only when the LPTIM is enabled. It will be automatically reset by hardware.
	//LPTIM_CR |= (1 << 1); //SNGSTRT: LPTIM start in Single mode
*/
    /* Loop forever */
	//for(;;);
//}

void LPTIM1_Set_Period(uint16_t period){
	//The LPTIM_ARR register must only be modified when the LPTIM is enabled (ENABLE bit set to ‘1’).
	LPTIM_ARR = period; //RR[15:0]: Auto reload value
}

void LPTIM1_Start_Continuous_Mode(){
	//LPTIM1 must be enabled first
	LPTIM_CR |= (1 << 2); //CNTSTRT: Timer start in Continuous mode This bit can be set only when the LPTIM is enabled. It will be automatically reset by hardware.
}

void LPTIM1_Enable(){
	LPTIM_CR |= (1 << 0); //ENABLE: LPTIM enable 1:LPTIM is enabled
}

void LPTIM1_Disable(){
	LPTIM_CR &= ~(1 << 0); //0:LPTIM is disabled
}

void initialize_LPTIM(){
	//For 1Hz, 128 * 255, With LSE clock LPTIM_ARR = 0x00FF;

	LPTIM_IER |= (1 << 1); //Bit 1 ARRMIE: Autoreload match Interrupt Enable
	//The LPTIM_CFGR register must only be modified when the LPTIM is disabled (ENABLE bit reset to ‘0’).
	LPTIM_CFGR &= ~(1 << 23); //COUNTMODE: counter mode enabled 0: the counter is incremented following each internal clock pulse
	LPTIM_CFGR &= ~(1 << 22); //PRELOAD: Registers update mode 0: Registers are updated after each APB bus write access
	LPTIM_CFGR &= ~(1 << 21); //WAVPOL: Waveform shape polarity 0: The LPTIM output reflects the compare results between LPTIM_CNT and LPTIM_CMP registers
	LPTIM_CFGR &= ~(1 << 20); //WAVE: Waveform shape WAVE bit to ‘0’ forces the LPTIM to generate either a PWM waveform
	LPTIM_CFGR &= ~(1 << 19); //TIMOUT: Timeout enable 0: A trigger event arriving when the timer is already started will be ignored
	LPTIM_CFGR &= ~(0x03 << 17); //TRIGEN[1:0]: Trigger enable and polarity 00: software trigger (counting start is initiated by software)
	LPTIM_CFGR |= (0x07 << 9); //PRESC[2:0]: Clock prescaler, 111: /128
	//LPTIM_CFGR |= (0x01 << 6); //Bits 7:6 TRGFLT[1:0]: Configurable digital filter for trigger
	//LPTIM_CFGR |= (0x01 << 3); //Bits 4:3 CKFLT[1:0]: Configurable digital filter for external clock
	LPTIM_CFGR &= ~(1 << 0); //CKSEL: Clock selector 0: LPTIM is clocked by internal clock source (APB clock or any of the embedded oscillators)
	//LPTIM_CR |= (1 << 0); //ENABLE: LPTIM enable 1:LPTIM is enabled
	LPTIM_CR |= BIT2; //CNTSTRT: Timer start in Continuous mode - Set before ENABLE
	LPTIM_CR |= (1 << 0); //ENABLE: LPTIM enable 1:LPTIM is enabled
	//LPTIM_ARR &= (0xFF); //Clear ARR[15:0]: Auto reload value
	LPTIM_ARR = 0x00FF; //RR[15:0]: Auto reload value
	while ((LPTIM_ISR & (1 << 4))==0); //Bit 4 ARROK: Autoreload register update OK
	LPTIM_ICR |= (1 << 4); //ARROKCF: Autoreload register update OK clear flag. Writing 1 to this bit clears the ARROK flag in the LPTIM_ISR register
	//LPTIM_CR |= (1 << 0); //ENABLE: LPTIM enable 1:LPTIM is enabled
	//LPTIM_CR |= (1 << 2); //CNTSTRT: Timer start in Continuous mode This bit can be set only when the LPTIM is enabled. It will be automatically reset by hardware.
}
